### ISSUE TITLE
Downloading .ipynb results in a .ipynb.txt file

### ISSUE THREAD

**Issue by bryeis** [executablebooks/sphinx-book-theme#105]
In my book as well as in the [documentation](https://jupyterbook.org/content-types/notebooks.html) if you click to download the source of a jupyter notebook in the upper right button, it seems to add a .txt extension to the .ipynb file.  I'm not sure if this is by design or a bug, I looked quickly and could not find it documented.

In the same documentation, there is a html link: "you can download the notebook content for this page." that results in downloading a notebook file (.ipynb) fine.

**Comment by raphaeltimbo** [comment]
It looks like https://jupyterbook.org/content-types/notebooks.html is having this issue again.
I was also having this problem when using the sphinx-book-theme and fixed by finding this issue here and applying the modification from the PR 656 referenced here (setting `html_sourcelink_suffix = ""` in my conf.py file).
