### ISSUE TITLE
Add [all] option for extras_requires

### ISSUE THREAD

**Issue by emdupre** [executablebooks/sphinx-book-theme#187]
**Is your feature request related to a problem? Please describe.**

Trying to [set up a development environment ](https://sphinx-book-theme.readthedocs.io/en/latest/contributing.html#set-up)for sphinx-book-theme, the recommended `pip install` command is not correctly installing the `extras_requires` packages. As a result, I get errors about uninstalled dependencies (like plotly) when running `nox -s docs`. In the end, I needed to do this:

`pip install -e .[code_style,sphinx,testing]`

But that seems overly verbose.

**Describe the solution you'd like**

We _could_ update the documentation just to mention the necessary extra installs. But I'd quite like to install combine the necessary extras_requires into one `[all]` option, using something like:

```python
# Enable a handle to install all extra dependencies at once
EXTRA_REQUIRES['all'] = list(set([
    v for deps in EXTRA_REQUIRES.values() for v in deps]))
```

You can [see it implemented here](https://github.com/ME-ICA/tedana/blob/387db319c6d59328f8642e0cd077c2000caf5b82/tedana/info.py#L59-L61).

Then it could be simply installed with `pip install -e .[all]`.

**Describe alternatives you've considered**

At a minimum, I think a documentation update will be helpful !

**Comment by choldgraf** [comment]
This seems reasonable to me - perhaps @chrisjsewell has experience with this before? But it could be pretty easy to add an extra line that's something like

```python
extras_requres["all"] = set(ii for jj in all_deps.values() for ii in jj)
```

**Comment by chrisjsewell** [comment]
> As a result, I get errors about uninstalled dependencies (like plotly) when running `nox -s docs`. In the end, I needed to do this:

> pip install -e .[code_style,sphinx,testing]

This doesn't make sense me though, because nox installs the packages into isolated virtual environments (in the `.nox` folder), so it should not matter what you install into your base environment, i.e. that pip install should not make any difference.

Have you tried deleting the `.nox` folder and re-running?

**Comment by emdupre** [comment]
Setting up a new conda environment, deleting the .nox folder, and re-running worked ! Sorry for the noise.

I'm ok to close if you'd prefer, but I think the `[all]` option could still be useful -- no strong feelings either way. Thanks !!

**Comment by choldgraf** [comment]
Hmm, what does removing the nox folder do? We should document that if this is a common gotcha.

**Comment by chrisjsewell** [comment]
I was going to bring this up in meta, since I've started adding `tox.ini` to repositories (see markdown-it-py and myst-parser).
Basically tox/nox are very helpful when switching between different repos/projects, to quickly run the tests and doc builds against multiple environments

The "normal" workflow for me before was to open up a repositories folder in VS Code, create a conda environment, install the package into it, then run `pytest`, `make html`, etc

With https://tox.readthedocs.io it doesn't preclude you from doing this, but offers an easier/quicker approach; you just have tox installed in your base environment (and optionally tox-conda when using conda). Then, when you open a new repo folder all you have to do is run `tox`.
Depending on your `tox.ini` and what python versions you have available, this will then create one or more virtual environments in a local `.tox` folder, then run the tests using each environment.
For example, with the [myst-parser tox.ini](https://github.com/executablebooks/MyST-Parser/blob/master/tox.ini) it runs: py36-sphinx2,py37-sphinx2,py38-sphinx2,py36-sphinx3,py37-sphinx3,py38-sphinx3,docs, by default, or you can run a single one with e.g. `tox -e py38-sphinx3`

To parse additional arguments to pytest, you just put them after a `--` (assuming this is setup in the `tox.ini`) e.g. `tox -e py38-sphinx3 -- -x path/to/test.py`

nox is less mature/widely used than tox, but builds on tox, by offering a more configurable execution process, due to using a "dynamic" python configuration file (nox.py) instead of a "static" file (tox.ini). This is needed here for running the live server.

> Hmm, what does removing the nox folder do? 

So getting back to your original question. If you delete the `.tox`/`.nox` folder you simply delete any previously built environments and tox/nox will rebuild them when called (you can also force a rebuild with `tox -r`.

**Comment by chrisjsewell** [comment]
Note we can add this kind of description to the new "Developer Tips and Tricks" section in https://github.com/executablebooks/meta/pull/97/files

**Comment by pradyunsg** [comment]
> (you can also force a rebuild with `tox -r`.

FWIW, nox does not reuse the environments by default -- I've set an option in this project's noxfile.py to make it do so (it's nice to not have to tell it to reuse the environments on every run once you have it set up). *right now* you can either delete the `.nox` folder or run nox with `--no-reuse-existing-virtualenvs`. :)

**Comment by emdupre** [comment]
> Note we can add this kind of description to the new "Developer Tips and Tricks" section

I think it'd be great to add this there ! I'm familiar with tox, but this is my first time encountering nox. Nice to know a bit more about what the differences are.

In my own workflow I set up separate conda environments for each project, so the `pip install` is less problematic for me. But I do think documenting _how_ to get a new virtual environment in this context, as @pradyunsg notes, will be really important.

**Comment by chrisjsewell** [comment]
I'm going to close this; after ef8815fb4a793747fd259098002da7117eabd2e6 nox is no longer used, and the documentation has been updated for tox (+ tox-conda). Using tox you should never need to manually install any extras.

**Comment by emdupre** [comment]
Ok then. Should I close https://github.com/executablebooks/jupyter-book/pull/898 as well ?

**Comment by chrisjsewell** [comment]
I'd say yes, unless you are strongly for it?
