### ISSUE TITLE
"Content" should be hidden at PDF Printing

### ISSUE THREAD

**Issue by ProfFan** [executablebooks/sphinx-book-theme#222]
**Is your feature request related to a problem? Please describe.**

When clicking the `Print to PDF` button, the contents navigation is not hidden, wasting page space.

**Describe the solution you'd like**

Add a CSS to hide it when printing.

**Describe alternatives you've considered**

Allow sphinx to generate chapter PDFs with LaTeX, but I don't know if this is possible.

**Additional context**

HTML:

![image](https://user-images.githubusercontent.com/5358374/94348539-24faf980-000b-11eb-99d5-456c9d29cc29.png)

Print Render:

![image](https://user-images.githubusercontent.com/5358374/94348551-40fe9b00-000b-11eb-975a-e74748fb59ca.png)

**Comment by choldgraf** [comment]
I think right now this is intentional, because you can click through to the underlying sections of the PDF if you're browsing the PDF with a computer (obviously doesn't work when it is printed). You can disable the TOC by adding some custom CSS of your own. Something like:

```
@media print {
  .bd-toc {
    display: none;  
  }
}
```

see https://jupyterbook.org/advanced/sphinx.html#custom-css-or-javascript for reference

**Comment by pradyunsg** [comment]
Would it make sense to make the TOC a start-of-document thing when printing, instead of having it off-to-the-side?

(yes, I know I'm not thinking about the implementation complexity)

**Comment by choldgraf** [comment]
yep - I think that'd be a reasonable thing to do (though I suspect it'll be a lot more complex if we have to re-arrange the DOM for printing)

**Comment by ProfFan** [comment]
I think that at least there should be a toggle switch (simple js that adds a class to the TOC with `@media print`) to hide it.

**Comment by choldgraf** [comment]
Mmm I think instead of adding a new configuration value we should add a section to the documentation to make this clearer so that folks can customize the layout of the printed web PDF as they wish. I just put together https://github.com/executablebooks/jupyter-book/pull/1031 so I'll close this issue when that is merged, and we can discuss other ideas like moving the TOC in-line with the page when printing in another issue
