### ISSUE TITLE
Carets should only be shown for part headers if they're collapsed by default

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#235]
After playing around with it a bit, I think that we should hide the carets for the "part" headers (the stuff that's defined in `:caption:`) if the top-level pages are shown by default.

If we *show* those carets when the top-level pages are always shown, then the caret will *always* be expanded on every page, which means that their only purpose would be if a user for some reason wanted to *close* a subset of pages (which would then be re-opened any time they clicked a link). I feel like that's an unlikely usage scenario (but let me know if you disagree), so the carets are providing visual distraction without much functionality in that case. So we should remove those carets if `show_navbar_depth > 0`.

@AakashGfude what do you think?

**Comment by AakashGfude** [comment]
@choldgraf your analysis makes sense. Carets for `show_navbar_depth > 0` does not server much purpose. And it also does not take away any functionality, as the "parts" can still be collapsed/uncollapsed by clicking on the title. 
If we can somehow make it more evident that the "parts" are clickable by design, then probably we can remove it altogether, But this can be kept for a different time.
