### ISSUE TITLE
Add badges and icon links to sidebar

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#285]
With the alabaster theme I like that you can have badges added to the sidebar (and a description), e.g.

![image](https://user-images.githubusercontent.com/2997570/107613512-c0061000-6c48-11eb-9261-44f3a7687822.png)

See https://github.com/bitprophet/alabaster/blob/master/alabaster/theme.conf for all options

### Implementation

The easiest way to do this would be to support the Icon Links functionality from the pydata theme:

- https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/header-links.html#icon-links

**Comment by ErikBjare** [comment]
You can modify the sidebar yourself by setting `html_sidebars`.

I discovered that was the case when I migrated from the rtd-theme, since I had it set and it made the sidebar use the old structure.

Example:
```py
# Custom sidebar templates, maps document names to template names.
html_sidebars = {
   "**": ["globaltoc.html", "relations.html", "sourcelink.html", "searchbox.html"],
}
```

Not sure what you need to set it to to keep the structure used in this theme, but should be easy for you to figure out :)
