### ISSUE TITLE
Improve CSS for API documentation

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#307]
In https://github.com/executablebooks/meta/discussions/286 @rscohn2 noticed that our CSS for API docs looks a bit wonky. @chrisjsewell pointed out that the CSS for this is here: https://github.com/executablebooks/sphinx-book-theme/blob/bdcf1065f0fbf92f786082b78c86af7a280651df/src/scss/_page.scss#L232-L234

so we should fix up the CSS there so that this type of API docs looks good!

**Comment by rscohn2** [comment]
I only have basic knowledge of CSS, but if someone could suggest what properties need to change I would like to try to fix this.

**Comment by pradyunsg** [comment]
Do you have examples of this wonky looking pages?

I'm looking at https://sphinx-themes.org/sample-sites/sphinx-book-theme/demo/api.html, and it seems OK to me on mobile.

**Comment by rscohn2** [comment]
I added a custom.css with the following contents to fix the problem. Not sure if this is appropriate as a general fix.

/* A workaround for https://github.com/readthedocs/sphinx_rtd_theme/issues/647
 * Override display for function signatures so that there is spacing between
 * types and arguments */
dt {
    display: table-cell !important;
}

**Comment by rscohn2** [comment]
Thanks for fixing it.
