### ISSUE TITLE
Add summary (table) of html_theme_options

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#361]
i.e. all the options in https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/theme.conf (and include their defaults)

If users are anything like me, they can't be bothered to read through all the customisation documentation to find the available keys 😉 

I think this should probably be on the front page, containing links to the particular sections that explain them in more detail

**Comment by choldgraf** [comment]
Agree that this is important documentation to have. A section / page like "Configuration reference" could contain a list that should be updated any time a new option is added.

More generally I think we should pass through these (and other) docs with an eye on [the reference guidelines from diataxis](https://diataxis.fr/reference/).

Meta-point: I am gonna remove myself from "assignees" because I'd rather not bottleneck myself as being the only one who can work on this. Something we should discuss w/ the team (perhaps in in a team meeting) is "what does it mean to assign somebody to an issue, and when should it happen?"

**Comment by chrisjsewell** [comment]
> I am gonna remove myself from "assignees" because I'd rather not bottleneck myself as being the only one who can work on this

That's fine. But... that being said, you are the one who has the most intimate/recent knowledge of the documentation (from #315), and this is a pretty quick win for users to more easily understand the available functionality of the theme.
So I would strongly recommend you do consider assigning yourself this as an upcoming priority
