### ISSUE TITLE
Allow the left navigation menu to collapse at the "part" level

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#460]
### Description

We allow the navigation of a site to collapse sub-sections within parent-sections. So section 3.2 is collapsed and toggle-able by clicking the arrow next to section 3

![chrome_CP4mbItWEV](https://user-images.githubusercontent.com/1839645/149239117-1c1bed79-d936-4c52-a863-129c1ee6caab.gif)

However, some documentation sites are structured as **parts** with captions denoting the title of each part. In the sidebar, the part titles are not clickable, and the first chapter in each part is the first "collapsible" header.

It would be useful if instead users could select to make the *part titles* collapsible as well. This would allow people to save some space in the left sidebar if they wished.

### Implementation guide

We currently use a combination of `label` + `input` to create a toggle button to the right of each menu item. These currently are applied to the nested `ul` and `li` items in the sidebar.

This is generated by the parent theme (pydata sphinx theme) here:

https://github.com/executablebooks/sphinx-book-theme/blob/22ce601805231c9cc2c9d63838f2d07ab1f0e5ed/sphinx_book_theme/__init__.py#L94-L102

and specifically the checkboxes are added here:

https://github.com/pydata/pydata-sphinx-theme/blob/5f9a497a1a58d659abe5de673f779bdacbbf57d5/src/pydata_sphinx_theme/__init__.py#L258

We could either make an upstream contribution (or hack a solution here) to make it optional to collapse items at the `part` level. I think there are two API things to consider:

- `show_nav_level` should support `0`, and in this case it would collapse all nav sections, including parts. ref: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#control-how-many-navigation-levels-are-shown-by-default
- `collapse_parts` could be a `bool` (to start, defaults to `False`) and if `True`, would trigger an extra `for` loop [around here](https://github.com/pydata/pydata-sphinx-theme/blob/5f9a497a1a58d659abe5de673f779bdacbbf57d5/src/pydata_sphinx_theme/__init__.py#L262-L264) that would loop through `part` captions, and add a checkbox to them. We'd also need to add some CSS to look for `checked` and hide the subsequent `ul` lists under each caption

example design: https://docs.microsoft.com/en-us/dotnet/core/introduction

also mentioned here: https://github.com/executablebooks/sphinx-book-theme/issues/390

**Comment by raphaelfournier** [comment]
Hello,
I would like to know what is the state of this feature for the `sphinx-book-theme`. It seems that the issue was closed because the enhancement was brought upstream in `pydata-sphinx-theme`. I followed the procedure for contributing to `sphinx-book-theme`, so I have an up-to-date version of the theme, ready for some customization.

However, I tried adding a `"show_nav_level": 0,` on line 125 in `docs/conf.py`, but it does not yield the expected behavior, _ie_, to collapse the sidebar at 'Topic areas' and 'References' (the titles associated with a "caption" in the toctree, from `docs/index.md`). Perhaps did I misunderstood what was supposed to happen, or how/where to place the option?

For full reference, my use case is that I'm porting an existing [course textbook](https://cedric.cnam.fr/vertigo/Cours/RCP216/) in Sphinx to jupyter-book (so I would in the end work with `_config.yml` and not `conf.py`, but I don't think it matters yet), and I'd like to have a chapter by lesson, organized in _collapsed_ parts.
