### ISSUE TITLE
RFE: please provide support for sphinx 5.x and pydata-sphinx-theme 0.9.0

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-book-theme#571]
https://github.com/executablebooks/sphinx-book-theme/blob/af6277a7276112ee915d901984193c49e56d5a76/pyproject.toml#L24-L26

**Comment by SilverRainZ** [comment]
On Arch Linux, I use Sphinx 5.x from the system path, and sphinx-book-theme from user path works fine with it, so I think we can just relax this constraint？

**Comment by kloczek** [comment]
Without patching that fragment you cannot pass typical pep517 build based process.
I've trimmed that line in my spec file and I don't see so far any negative symptoms using such product however I've been using produced package only to build another three other packages
```console
[tkloczko@devel-g2v SPECS]$ grep sphinx-book-theme * -l
python-dask-sphinx-theme.spec
python-myst-nb.spec
python-pooch.spec
python-sphinx-book-theme.spec
```

**Comment by pradyunsg** [comment]
x-ref https://github.com/executablebooks/meta/issues/750

There's a checklist on that issue. Contributions are welcome. :)

**Comment by pradyunsg** [comment]
I've filed #575 for tracking the pydata upgrade (there's an open PR for it, and this issue is broader than that) and the meta issue is already tracking Sphinx 5 support across the executablebooks org, so I'm gonna go ahead and close this.

Thanks for chiming in with context on how Sphinx 5 + sphinx book theme is working for you @SilverRainZ! ^>^

**Comment by kloczek** [comment]
Issue still is not resolved
https://github.com/executablebooks/sphinx-book-theme/blob/443c7a7167cc39bffa4b41079e6db96490cf98af/pyproject.toml#L61
