### ISSUE TITLE
Allow inline elements in sidenotes

### ISSUE THREAD

**Issue by oyamauchi** [executablebooks/sphinx-book-theme#612]
### Context

When `use_sidenotes` is true and footnotes are converted to sidenotes, inline elements within the footnote content are stripped. When `use_sidenotes` is false, the inline elements show up as-is within the footnote. This means you can't even have bold or italics in sidenotes, which seems like a needless restriction.

Illustration:

<img width="1082" alt="with sidenotes on" src="https://user-images.githubusercontent.com/107014/190709082-90d1b46c-15d3-40a1-9de1-8df697e11deb.png">

<img width="834" alt="with sidenotes off" src="https://user-images.githubusercontent.com/107014/190709087-547b8c3f-c466-47f3-bbff-92cd5b19e56b.png">

### Proposal

I'm not familiar with the details of Sphinx or Docutils, so I'm not sure how big of a task this is. As far as I can tell it's because of the call to `astext()` here:

https://github.com/executablebooks/sphinx-book-theme/blob/master/src/sphinx_book_theme/_transforms.py#L34

**Comment by choldgraf** [comment]
cc @AakashGfude could you look into this one? I think we might have a bug in the sidenotes code

**Comment by AakashGfude** [comment]
Thanks @oyamauchi for reporting this. Will have a look.

**Comment by AakashGfude** [comment]
Hi @oyamauchi @choldgraf, actually it's not a bug. But a limitation on the sidenote elements. The sidenotes are an inline `span` tag, so it cannot have other markup like bold or italic inside it. 
Details on why `span` tag was chosen: https://github.com/executablebooks/sphinx-book-theme/pull/546#issue-1186418914

**Comment by s-bear** [comment]
I was just trying to figure out why a link was disappearing from a sidenote and found this. I wanted to add that I had equations in footnotes that broke when I enabled sidenotes. While attempting to fix things I disabled `dollarmath` and configured MathJax directly, which works. After reading this issue, I think it's because MathJax processes everything after Sphinx, so the dollar-delimited math regions survive the `astext()` call. Since MathJax works in sidenotes, I assume that whatever it does is also considered an inline element and shouldn't be stripped out?

With `dollarmath`:
![with-dollar-math](https://user-images.githubusercontent.com/4016348/199398451-0ace9583-d9ef-4437-a58a-ee3a7b3540ed.png)
Without `dollarmath`:
![no-dollar-math](https://user-images.githubusercontent.com/4016348/199399186-ce922e1d-8d35-4746-985b-63165d5fcc47.png)

Source (Markdown, with the `deflist` extension):
```
$\mat{\Gamma} \in \RR^{N\times N}$
: is the Tikhonov matrix. $\mat{\Gamma} = \alpha \mat{I}$ yields the standard ridge regression, which penalises solutions with large L-2 norm and selects lower "energy" solutions. Setting $\mat{\Gamma} = \mat{I}\ast h$, where $\ast$ is convolution and $h$ is a high-pass filter kernel[^note-convolution], penalises solutions with content above $h$'s frequency cut-off and thus selects lower-frequency, smooth solutions.

[^note-convolution]: Here, $h \in \RR^{1 \times n}$ is a row vector and $(\mat{I} \ast h)\_{i,j}$ $= h\_{i-j+\lceil n/2\rceil}$, or zero if the index is out of bounds.
```
For posterity, note that I also had to escape the underscores (e.g. `$= h\_{ ... }$`) for this to render correctly after disabling `dollarmath` but that's (probably?) unrelated to the issue at hand. I also manually set my `mathjax3_config` in `conf.py` so that I can add tex macros. I added the `'inlineMath'` entry to it after disabling `dollarmath` to get things working again:
```
mathjax3_config = { 'tex': {
		'inlineMath': [['$','$'],['\\(','\\)']], # added after disabling 'dollarmath'
		'macros': {
			'RR': '\\mathbb{R}', # real numbers
			'mat': ['\\mathbf{#1}',1], #matrix: bold, upright
			'trans': '\\intercal', #transpose T
		},
	}}
```
