### ISSUE TITLE
✨ Release candidate ✨ v1.0.0

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#686]
Try out the release candidate for this theme here:

https://github.com/executablebooks/sphinx-book-theme/releases/tag/v1.0.0rc1

Install with

```
pip install -U --pre sphinx-book-theme
```

If you see anything wrong, open an issue and cross-link it here! (or just comment if you wish)

This one makes a number of breaking changes, so I'm bumping the major version (see #670 which this will close when it is released).

**Comment by mathbunnyru** [comment]
That's great news!

I've built our docs with a new version and in general, they look amazing I love the new features and bug fixes.

PR: https://github.com/jupyter/docker-stacks/pull/1855
Docs: https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/index.html

I've found some problems I suppose:

1. https://github.com/executablebooks/sphinx-book-theme/issues/545

This issue seems to be back.
https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/index.html#contributing

It's impossible to have `Contributing` section highlighted in the Contents section.

2. https://github.com/executablebooks/sphinx-book-theme/issues/671

The title is still missing.
If it is designed to be missing, the blank space above the logo should be decreased slightly.

3. I actually prefer old colors in the bash sections, but that's just my opinion.
New: https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/using/running.html
Old: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/running.html

4. `Last updated on None.` at the bottom of each page.
I don't know how this feature works exactly, so it might not be a bug.

5. If I scroll up, being already on top of the page, on Safari, I see "Skip to main content". I guess this is a feature for mobile devices, but I'm using desktop Safari on macOS.

Let me know if I should reopen issues for 3-5, and please reopen 1-2 if you consider them to be issues.

**Comment by choldgraf** [comment]
Thanks for these comments @mathbunnyru - a few responses below

> - regarding https://github.com/executablebooks/sphinx-book-theme/issues/545

I tried your link (https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/index.html#contributing) and it worked fine for me. The correct section was highlighted. Can you try again and make sure you refresh the page or something to make sure the CSS is loaded?

> - regarding the logo title

Here's the behavior:

- If any logo image is set, then you must manually specify HTML logo text in `html_theme_options.logo.text`

So I suspect that in your case, this is not manually set.

In either case, I've got a PR open that tightens up the whitespace in the sidebar so that the logo has more equal spacing around it if it's text (or an image). Want to give that a shot?

> bash coloring

I'm afraid this one we can't easily change. The pygments theme was updated to be more accessibility-friendly. If you want those defaults changed I'd recommend that you open an issue in the pydata theme repository.

> last updated on

I'm not sure why it is `None` for you, but I opened this PR to remove the template if `last_updated` is not defined here:

- https://github.com/pydata/pydata-sphinx-theme/pull/1201

**Comment by mathbunnyru** [comment]
> I tried your link (https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/index.html#contributing) and it worked fine for me. The correct section was highlighted. Can you try again and make sure you refresh the page or something to make sure the CSS is loaded?

I tried Safari private tab and Vivaldi (Chromium-based browser) and tried to click different parts of content section.
Well, sometimes it works, and sometimes it doesn't.
When I first click "Quick Start" and then "Contributing", it instead tells me I'm reading "Maintainer Help Wanted" section.

> If any logo image is set, then you must manually specify HTML logo text in html_theme_options.logo.text

I added it, and it works, thank you 👍 

> In either case, I've got a PR open that tightens up the whitespace in the sidebar so that the logo has more equal spacing around it if it's text (or an image). Want to give that a shot?

If you could make a new RC release, I will definitely check this.

> bash coloring

Ok, I think let's keep the defaults, it's important to be more accessibility-friendly.

> last updated on

Great, I think this problem will be gone after a new release.
And I hope we will have this information for our docs, it's quite nice to have.

**Comment by choldgraf** [comment]
OK I'll make an RC now. I also opened this to track the "skip to content" button issues:

- https://github.com/pydata/pydata-sphinx-theme/issues/1205

FYI it looks like in general, there is different behavior with Safari than with Chrome/Firefox...that might mean it'll take more digging in the future to sort out how to resolve this.

**Comment by mathbunnyru** [comment]
Thank you, @choldgraf.
There is less space wasted above the logo, so it looks better know 👍

**Comment by PhilipVinc** [comment]
I've tried this out. I noticed that for a `jpg` logo in the left sidebar the `height: 100%` css attribute from pydata makes it so that the logo is stretched vertically...

<img width="2061" alt="Screenshot 2023-02-21 alle 11 06 54" src="https://user-images.githubusercontent.com/2407108/220314509-64180b68-43a1-42b1-9b87-15b2b300a684.png">

**Comment by choldgraf** [comment]
Shit good catch! Can you find a CSS rule that makes it keep the same aspect ratio? I won't be at a computer for a while but am happy to merge a PR!

**Comment by PhilipVinc** [comment]
Disabling `height: 100%` works (there is still `width :100%` ) but I am really not an expert of css so I have no idea if that is a good solution...

**Comment by choldgraf** [comment]
@PhilipVinc i think this should fix it, could you try it out?

- https://github.com/executablebooks/sphinx-book-theme/pull/689

**Comment by martinfleis** [comment]
I've noticed that with the RC, the long links in the navbar are wrapped if they are longer than the width of the navbar even if the are "one word" now. See the screenshot from the docs of https://github.com/xarray-contrib/xvec rendered with the stable and with RC.
RC:
![Screenshot 2023-03-01 at 10 36 11](https://user-images.githubusercontent.com/36797143/222100425-039f0773-71b4-453f-a2bf-2d34d62fd711.png)
stable:
![Screenshot 2023-03-01 at 10 36 29](https://user-images.githubusercontent.com/36797143/222100499-3ed6d756-a625-4ef3-a22e-22f41e948182.png)

Is there a way to control this? Was it intended? I think that for the API, the old way is much better.

**Comment by choldgraf** [comment]
hmmm, yep - that change was intentional, because a few other projects had reported it as a bug that the words _weren't_ wrapping and were being cut off.

Here's the change that modified this, I believe:

https://github.com/pydata/pydata-sphinx-theme/pull/1191/files#diff-138e42ae7155057d1d55db042d39b92a61e05b341948df34d298d1690878006dR43-R44

For now, I suggest that you add a little custom CSS rule that undoes this change if you'd like them to instead be cut off, if we get more reports from others that prefer "cutoff" vs. "word wrap" then we could change it back.

**Comment by martinfleis** [comment]
Thanks! I'll override it for now. Maybe it may be worth adding an option for that?

**Comment by choldgraf** [comment]
The tricky thing is that it's hard to add options that control _CSS_. In the meantime I'll add a note in the CHANGELOG with the rule in case others want to revert it.
