### ISSUE TITLE
No right sidebar page width

### ISSUE THREAD

**Issue by adamgayoso** [executablebooks/sphinx-book-theme#736]
### Describe the bug

When there is no header for a right sidebar, the width of the main content collapses

https://docs.scvi-tools.org/en/latest/api/index.html

<img width="1340" alt="Screenshot 2023-05-25 at 9 29 13 AM" src="https://github.com/executablebooks/sphinx-book-theme/assets/10859440/a4210119-8437-4414-b64b-fb790021dbbd">

### Reproduce the bug

Have a simple page with only a top-level heading.

**Comment by sneakers-the-rat** [comment]
Adding to this - the fix seems simple enough. 

The problem seems to come from the `bd-content` container not having its `flex-direction` set. The default is `row` so the footer is positioned to the right of the page content rather than beneath it

(eg https://jupyterbook.org/en/stable/content/citations.html )

<img width="2000" alt="Screen Shot 2023-06-26 at 1 03 44 PM" src="https://github.com/executablebooks/sphinx-book-theme/assets/12961499/1f80a071-2491-4748-93c5-1d7dcf1ae1e8">

If you instead manually set `flex-direction: column` then the page is laid out as expected:

<img width="1999" alt="Screen Shot 2023-06-26 at 1 05 32 PM" src="https://github.com/executablebooks/sphinx-book-theme/assets/12961499/ddfc9cfe-92e5-41ea-8401-e39d774c47d3">

It seems like this is a `pydata-sphinx-theme` problem though, specifically the column mode would need to go here: https://github.com/pydata/pydata-sphinx-theme/blob/bc82874fe6b966cc8700f32fb38d2f6a536d22ae/src/pydata_sphinx_theme/assets/styles/sections/_article.scss#L10

But I don't know enough about this theme, that theme, and how they interact to know if that would be something that should go there or here. 

The PR seems trivial, just one changed CSS value, so I can make that either here or there depending on what maintainers think would be better, but ya would be nice to fix bc i'm just doing this downstream atm

**Comment by flying-sheep** [comment]
@sneakers-the-rat nope, what you see is #742. The next/prev footer isn’t supposed to be a direct child of `.bd-content`
