### ISSUE TITLE
Use beautifulsoup for testing

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#75]
In many of the tests we are just seeing if some text made it into the HTML at all. That usually works, but it'd be better to zero-in on the specific part of the page we want to test and use beautifulsoup to confirm what is in there

**Comment by pauleveritt** [comment]
FWIW I do that when doing TDD on my Sphinx extensions and it works really well. I doubt you need any pointers but let me know if I can help.

**Comment by choldgraf** [comment]
Nice - thanks for the feedback! We've started migrating tests to BS here and there, still have a little ways to go though :-)

**Comment by pauleveritt** [comment]
I can propose some fixture kinds of things to make automation easier in `test_build.py` if you'd like.

**Comment by choldgraf** [comment]
That would be great! 😊

**Comment by pauleveritt** [comment]
My `tests/sphinx/conftest.py` looks like this:

```python
import os
from pathlib import Path
from shutil import rmtree

import pytest
from bs4 import BeautifulSoup
from sphinx.testing.path import path

pytest_plugins = [
    'sphinx.testing.fixtures',
]


@pytest.fixture(scope='session')
def remove_sphinx_projects(sphinx_test_tempdir):
    # Even upon exception, remove any directory from temp area
    # which looks like a Sphinx project. This ONLY runs once.
    roots_path = Path(sphinx_test_tempdir)
    for d in roots_path.iterdir():
        if d.is_dir():
            build_dir = Path(d, '_build')
            if build_dir.exists():
                # This directory is a Sphinx project, remove it
                rmtree(str(d))

    yield


@pytest.fixture()
def rootdir(remove_sphinx_projects):
    roots = path(os.path.dirname(__file__) or '.').abspath() / 'roots'
    yield roots


@pytest.fixture()
def content(app):
    app.build()
    yield app


@pytest.fixture()
def page(content, request) -> BeautifulSoup:
    pagename = request.param
    c = (content.outdir / pagename).text()

    yield BeautifulSoup(c, 'html.parser')
```

I then have `tests/sphinx/roots/test-hello-resource` directories for each Sphinx configuration I want to test (a conf.py, index.rst, etc.)

For each of those, I have `test_hello_resource.py` which looks like this (most basic case):

```python
from bs4.element import Tag
import pytest

pytestmark = pytest.mark.sphinx('html', testroot='hello-resource')


@pytest.mark.parametrize('page', ['index.html', ], indirect=True)
class TestHelloResource:

    def test_index(self, page):
        heading: Tag = page.select_one('h1')
        assert 'index' == heading.text
        body: Tag = page.select_one('div')
        assert 'Hello World' in body.text
```

Because all the Sphinx work has been done once per module (`scope='session'`), each test method is fast, so I write a lot of test_* tests for various specific units I want to reason about on a page.

It took me a long time to trial-by-error a working config that was fast but didn't over-cache. It's possible this approach is also flawed.

That said, I'm pretty far into a radical Sphinx overhaul and I almost never open a browser, I just sit in PyCharm and do TDD, run tests under the debugger, and it's a lot of fun.

**Comment by pauleveritt** [comment]
I should also add, I haven't checked in the last 18 months whether things changed in `sphinx.testing.fixtures`. There might have been something I missed. (Although I'm developing against latest release.)

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/MyST-Parser/blob/f32bd380bdec755238566fa91352f9ed1d491036/tests/test_sphinx/conftest.py#L60:88

**Comment by chrisjsewell** [comment]
This was finalised in ef8815fb4a793747fd259098002da7117eabd2e6
