### ISSUE TITLE
Single-page documentation (\wout `toctree`)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#93]
As with pandas-dev/pydata-sphinx-theme#180, but more acute because the right "on this page" section seems to disappear as you scroll down the page: https://sphinx-panels.readthedocs.io/en/sphinx-book-theme/?

**Comment by choldgraf** [comment]
I just added this section to the docs about a single-page theme: https://sphinx-book-theme.readthedocs.io/en/latest/configure.html#use-a-single-page-version-of-this-theme

In this case, the disappearing right TOC is intentional in order to make sure it doesn't overlap with any content that expands into the right margin (you can hover over it in order to show the TOC again).

Perhaps we can include a configuration value like `always_show_toc` that makes the TOC *never* go away? Though in that case it would overlap with any margin content so it'd be at the user's risk.

**Comment by chrisjsewell** [comment]
Ok yeh ta that stops the error pandas-dev/pydata-sphinx-theme#180, but hovering over the ToC still doesn't work (at least building locally).
`always_show_toc` should definitely be an option. I don't know if this is at all possible, but ideally in this mode the ToC would actually switch to being on the right.

**Comment by choldgraf** [comment]
ah so in your mind, if it's a single page then the TOC should be on the left instead of the right? That shouldn't be *too* hard.

Hmmm, if hovering over the TOC doesn't work then that's a problem. Does it show up when the page first loads (when you're at the top?)

**Comment by chrisjsewell** [comment]
> Does it show up when the page first loads (when you're at the top?)

It did with `single_page=False`, it does not with  `single_page=True`

**Comment by chrisjsewell** [comment]
Might be due to:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/2997570/82156662-65d04e00-9874-11ea-8817-73b68ce5cdef.png">

**Comment by choldgraf** [comment]
Hmm - it seemed to work OK for me.

If I check out your `sphinx-book-theme` branch, remove the `toctree` in `index`, and add `single_page: True` to `conf.py` then this is what I see:

![image](https://user-images.githubusercontent.com/1839645/82160045-5c7cbc80-9847-11ea-8cc1-416b9708a382.png)

What browser are you on? And can you try with master on SBT? Maybe we need to make a release there?

**Comment by choldgraf** [comment]
I just pushed the update to your `sphinx-book-theme` branch and the toctree renders fine for me, so maybe it is a browser problem after all?

https://sphinx-panels.readthedocs.io/en/sphinx-book-theme/

**Comment by chrisjsewell** [comment]
Yep its working as advertised now 👍
